apiVersion: v1
kind: Pod
metadata:
  name: nginx 
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - name: service-secret-dir
        mountPath: /etc/secrets
  volumes:
  - name: service-secret-dir
    secret:
      secretName: redis-service-secret
