apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: redis-service-instance
  namespace: default
spec:
  # References service name and plan name
  clusterServiceClassExternalName: dcs-redis
  clusterServicePlanExternalName: SingleNode
  # Additional parameters can be added here,
  # which may be used by the service broker.
  parameters:
    name: "RedisSingleNode"
    password: "Password1234!"
